# Generated by Django 5.0.6 on 2024-05-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symboling', models.IntegerField()),
                ('wheelbase', models.FloatField()),
                ('carlength', models.FloatField()),
                ('carwidth', models.FloatField()),
                ('carheight', models.FloatField()),
                ('curbweight', models.FloatField()),
                ('horsepower', models.FloatField()),
                ('peakrpm', models.IntegerField()),
                ('citympg', models.FloatField()),
                ('highwaympg', models.FloatField()),
                ('fueltype', models.CharField(choices=[('gas', 'Gas'), ('diesel', 'Diesel')], max_length=6)),
                ('carbody', models.CharField(choices=[('convertible', 'Convertible'), ('hardtop', 'Hardtop'), ('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('wagon', 'Wagon')], max_length=11)),
                ('enginetype', models.CharField(choices=[('dohc', 'DOHC'), ('dohcv', 'DOHCV'), ('l', 'L'), ('ohc', 'OHC'), ('ohcf', 'OHCF'), ('ohcv', 'OHCV'), ('rotor', 'Rotor')], max_length=5)),
                ('CarCompanyName', models.CharField(choices=[('alfa-romeo', 'Alfa Romeo'), ('audi', 'Audi'), ('bmw', 'BMW'), ('buick', 'Buick'), ('chevrolet', 'Chevrolet'), ('dodge', 'Dodge'), ('honda', 'Honda'), ('isuzu', 'Isuzu'), ('jaguar', 'Jaguar'), ('mazda', 'Mazda'), ('mercury', 'Mercury'), ('mitsubishi', 'Mitsubishi'), ('nissan', 'Nissan'), ('peugeot', 'Peugeot'), ('plymouth', 'Plymouth'), ('porsche', 'Porsche'), ('renault', 'Renault'), ('saab', 'Saab'), ('subaru', 'Subaru'), ('toyota', 'Toyota'), ('volkswagen', 'Volkswagen'), ('volvo', 'Volvo')], max_length=15)),
                ('predicted_price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
